### ISSUE TITLE
Question about AFNP & APNB in Fig3

### ISSUE THREAD

**Issue by ggjy** [MendelXu/ANN#1]
Gook work!
I have some places that I don’t quite understand.  AFNB in Sec 3.3 E.q.(14-16) seems there is no key value transormation (θ/φ), its more like APNB in Fig. 3. And the APNB in Sec 3.2 seems to match the AFNB in Fig. 3. Is something that I misunderstand?

**Comment by jessemelpolio** [comment]
Thanks for your kind reminder. In our settings, we use the same key and value transformation for APNB. It could be left as an option for your cases. This design is inspired from OCNet, and it actually works for our network and can save a considerable amount of parameters and computation. I will revise relevant sections to make this design more clear. Sorry for the misleading and thanks for your careful reading.

**Comment by ggjy** [comment]
Thanks for your reply~
