### ISSUE TITLE
Losses

### ISSUE THREAD

**Issue by bluesky314** [MendelXu/ANN#10]
Your losses.py at https://github.com/MendelXu/ANN/blob/master/models/seg/loss/seg_modules.py has a number of different loss functions including some for embedding layers which are not mentioned in your paper. Could you kindly provide some explanation for what these losses mean? Would love to learn more about them, they seem quite interesting. Thanks!

**Comment by bluesky314** [comment]
@MendelXu You referenced you used hard-mining strategy and referenced to the PSPnet paper, however PSPnet has no hard-mining losses like you. Can you please clarify your reference and the source of the losses?

**Comment by MendelXu** [comment]
> Your losses.py at https://github.com/MendelXu/ANN/blob/master/models/seg/loss/seg_modules.py has a number of different loss functions including some for embedding layers which are not mentioned in your paper. Could you kindly provide some explanation for what these losses mean? Would love to learn more about them, they seem quite interesting. Thanks!

Sorry for the late reply. Although there are many loss functions provided in this file, we don't use those such as FocalLoss, Encoding Loss.  It is just cloned from https://github.com/donnyyou/torchcv. If you are interested in that, maybe you can refer to the original repository.

> @MendelXu You referenced you used hard-mining strategy and referenced to the PSPnet paper, however PSPnet has no hard-mining losses like you. Can you please clarify your reference and the source of the losses?

I'm sorry it is not very clear in our paper but We didn't refer the hard minging strategy to PSPNet.  It appears frequently in semantic segmentation repository and we don't find the source of that. If you find the source of that, may you post here? And we'll correct it in our paper

**Comment by bluesky314** [comment]
Thanks for clarification. Can you tell what online hard minning you did? Is
it only focal loss or something else as well?

**Comment by MendelXu** [comment]
You can refer to this function.https://github.com/MendelXu/ANN/blob/f4eabeb27dbba5c9bdcf83d03776bffa34995666/models/seg/loss/seg_modules.py#L58
It just computes the loss of the pixels which are hard.
Focal loss should work too, but we didn't try this.
