### ISSUE TITLE
精度

### ISSUE THREAD

**Issue by swjtulinxi** [MendelXu/ANN#12]
你好作者请问你实现了这个吗，我实现了ccnet danet ocnet annn这几个基于non-local原理的模型，发现结果反而更差，我不知道为什么，请问是否和torch的版本有关，或者是训练的图片长宽必须是偶数还是奇数有关系啊？？

**Comment by swjtulinxi** [comment]
作者你好，不知道为什么用了afnb和apnb模块会比只用apnb模块差很多，感觉是不是afnb模块反而会对精度有影响啊？？？

**Comment by MendelXu** [comment]
Sorry for late reply... The notification email is marked as spam by my school email.  You can refer to Appendix C in our [paper](https://arxiv.org/pdf/1908.07678.pdf) for some experience on how the experiment environment affects the performance.  Or may you report more details about your experiment environment and the dataset? It is my pleasure to help you solve the problem. Feel free to send me an email directly.
