### ISSUE TITLE
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by vanpersie32** [MendelXu/ANN#13]
See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Traceback (most recent call last):
  File "/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 946, in _build_extension_module
    check=True)
  File "/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 182, in <module>
    runner = method_selector.select_seg_method()
  File "/home/docker/data/licong/ANN/methods/method_selector.py", line 104, in select_seg_method
    return SEG_METHOD_DICT[key](self.configer)
  File "/home/docker/data/licong/ANN/methods/seg/fcn_segmentor.py", line 44, in __init__
    self._init_model()
  File "/home/docker/data/licong/ANN/methods/seg/fcn_segmentor.py", line 47, in _init_model
    self.seg_net = self.seg_model_manager.semantic_segmentor()
  File "/home/docker/data/licong/ANN/models/seg/model_manager.py", line 38, in semantic_segmentor
    model = SEG_MODEL_DICT[model_name](self.configer)
  File "/home/docker/data/licong/ANN/models/seg/nets/annn.py", line 17, in __init__
    self.backbone = BackboneSelector(configer).get_backbone()
  File "/home/docker/data/licong/ANN/models/backbones/backbone_selector.py", line 31, in get_backbone
    model = ResNetBackbone(self.configer)(**params)
  File "/home/docker/data/licong/ANN/models/backbones/resnet/resnet_backbone.py", line 176, in __call__
    orig_resnet = self.resnet_models.deepbase_resnet101()
  File "/home/docker/data/licong/ANN/models/backbones/resnet/resnet_models.py", line 256, in deepbase_resnet101
    norm_type=self.configer.get('network', 'norm_type'), **kwargs)
  File "/home/docker/data/licong/ANN/models/backbones/resnet/resnet_models.py", line 107, in __init__
    ('bn1', ModuleHelper.BatchNorm2d(norm_type=norm_type)(64)),
  File "/home/docker/data/licong/ANN/models/tools/module_helper.py", line 89, in BatchNorm2d
    from encoding.nn import BatchNorm2d
  File "/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/encoding/lib/__init__.py", line 27, in <module>
    build_directory=gpu_path, verbose=False)
  File "/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 863, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 959, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'enclib_gpu': [1/7] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include -isystem /data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/TH -isystem /data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /data/yicong.lc/anaconda2/envs/py36_ann/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/docker/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/encoding/lib/gpu/nms_kernel.cu -o nms_kernel.cuda.o
FAILED: nms_kernel.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include -isystem /data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/TH -isystem /data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /data/yicong.lc/anaconda2/envs/py36_ann/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/docker/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/encoding/lib/gpu/nms_kernel.cu -o nms_kernel.cuda.o
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/pytypes.h:1165:206: error: expansion pattern ‘pybind11::detail::negation<std::is_same<pybind11::detail::bools<pybind11::detail::negation<std::is_base_of<pybind11::arg, Args> >::value ..., pybind11::detail::negation<std::is_same<pybind11::detail::kwargs_proxy, Args> >::value ..., true>, pybind11::detail::bools<true, pybind11::detail::negation<std::is_base_of<pybind11::arg, Args> >::value ..., pybind11::detail::negation<std::is_same<pybind11::detail::kwargs_proxy, Args> >::value ...> > >::value’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/pytypes.h:1165:215: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/pytypes.h:1165:392: error: expansion pattern ‘pybind11::detail::negation<std::is_same<pybind11::detail::bools<pybind11::detail::negation<std::is_base_of<pybind11::arg, Args> >::value ..., pybind11::detail::negation<std::is_same<pybind11::detail::kwargs_proxy, Args> >::value ..., true>, pybind11::detail::bools<true, pybind11::detail::negation<std::is_base_of<pybind11::arg, Args> >::value ..., pybind11::detail::negation<std::is_same<pybind11::detail::kwargs_proxy, Args> >::value ...> > >::value’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/pytypes.h:1165:395: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/pytypes.h:1165:397: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/pytypes.h:1165:397: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/pytypes.h:1165:412: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:766:149: error: expansion pattern ‘std::is_copy_constructible<_Tp>::value’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:766:240: error: expansion pattern ‘std::is_same<typename Container::value_type&, typename Container::reference>::value’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:766:249: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:766:249: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:766:312: error: expansion pattern ‘std::is_copy_constructible<_Tp>::value’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:766:403: error: expansion pattern ‘std::is_same<typename Container::value_type&, typename Container::reference>::value’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:766:406: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:766:406: error: template argument 3 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:766:408: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:766:408: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:766:423: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:766:425: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:960:126: error: expansion pattern ‘pybind11::detail::negation<std::is_same<CharT, char> >’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:960:170: error: expansion pattern ‘pybind11::detail::negation<std::is_same<CharT, char16_t> >’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:960:214: error: expansion pattern ‘pybind11::detail::negation<std::is_same<CharT, char32_t> >’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:960:257: error: expansion pattern ‘pybind11::detail::negation<std::is_same<CharT, wchar_t> >’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:960:260: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:960:260: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:960:260: error: template argument 3 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:960:260: error: template argument 4 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:960:262: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1250:138: error: expansion pattern ‘pybind11::detail::negation<std::is_same<CharT, char> >’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1250:186: error: expansion pattern ‘pybind11::detail::negation<std::is_same<CharT, char16_t> >’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1250:234: error: expansion pattern ‘pybind11::detail::negation<std::is_same<CharT, char32_t> >’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1250:281: error: expansion pattern ‘pybind11::detail::negation<std::is_same<CharT, wchar_t> >’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1250:284: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1250:284: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1250:284: error: template argument 3 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1250:284: error: template argument 4 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1250:286: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1250:301: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1250:303: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1261:121: error: expansion pattern ‘pybind11::detail::negation<std::is_same<CharT, char> >’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1261:169: error: expansion pattern ‘pybind11::detail::negation<std::is_same<CharT, char16_t> >’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1261:217: error: expansion pattern ‘pybind11::detail::negation<std::is_same<CharT, char32_t> >’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1261:264: error: expansion pattern ‘pybind11::detail::negation<std::is_same<CharT, wchar_t> >’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1261:267: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1261:267: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1261:267: error: template argument 3 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1261:267: error: template argument 4 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1261:269: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1261:284: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1261:286: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:112: error: expansion pattern ‘std::is_void<_Tp>’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:137: error: expansion pattern ‘std::is_pointer<_Tp>’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:164: error: expansion pattern ‘std::is_reference<_Tp>’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:187: error: expansion pattern ‘std::is_const<_Tp>’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:190: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:190: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:190: error: template argument 3 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:190: error: template argument 4 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:192: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:201: error: expected parameter pack before ‘...’
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:251: error: expansion pattern ‘pybind11::detail::negation<pybind11::detail::is_copy_constructible<T1> >::value’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:294: error: expansion pattern ‘std::is_move_constructible<_Tp>::value’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:392: error: expansion pattern ‘std::is_same<decltype (declval<pybind11::detail::type_caster<typename pybind11::detail::intrinsic_type<T>::type, void> >().operator T&()), T&>::value’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:401: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:401: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:401: error: template argument 3 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:401: error: template argument 4 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:453: error: expansion pattern ‘std::is_void<_Tp>’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:478: error: expansion pattern ‘std::is_pointer<_Tp>’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:505: error: expansion pattern ‘std::is_reference<_Tp>’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:528: error: expansion pattern ‘std::is_const<_Tp>’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:531: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:531: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:531: error: template argument 3 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:531: error: template argument 4 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:533: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:542: error: expected parameter pack before ‘...’
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:592: error: expansion pattern ‘pybind11::detail::negation<pybind11::detail::is_copy_constructible<T1> >::value’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:635: error: expansion pattern ‘std::is_move_constructible<_Tp>::value’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:733: error: expansion pattern ‘std::is_same<decltype (declval<pybind11::detail::type_caster<typename pybind11::detail::intrinsic_type<T>::type, void> >().operator T&()), T&>::value’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:736: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:736: error: template argument 3 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:736: error: template argument 4 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:736: error: template argument 5 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:738: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:738: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:753: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1583:755: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1590:121: error: expansion pattern ‘std::is_void<_Tp>’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1590:146: error: expansion pattern ‘std::is_pointer<_Tp>’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1590:173: error: expansion pattern ‘std::is_reference<_Tp>’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1590:196: error: expansion pattern ‘std::is_const<_Tp>’ contains no argument packs
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1590:199: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1590:199: error: template argument 2 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1590:199: error: template argument 3 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1590:199: error: template argument 4 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1590:201: error: template argument 1 is invalid
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1590:210: error: expected parameter pack before ‘...’
/data/yicong.lc/anaconda2/envs/py36_ann/lib/python3.6/site-packages/torch/lib/include/pybind11/cast.h:1590:250: error: expansion pattern ‘pybind11::detail::negation<pybind11::detail::move_always<T> >::value’ contains no argument packs

**Comment by vanpersie32** [comment]
@MendelXu

**Comment by MendelXu** [comment]
Please install pytorch and torch-encoding denoted in the readme. You can refer to https://github.com/zhanghang1989/PyTorch-Encoding/issues/157
