### ISSUE TITLE
sim_map = (self.key_channel**-.5) * sim_map

### ISSUE THREAD

**Issue by swjtulinxi** [MendelXu/ANN#14]
sim_map = (self.key_channel**-.5) * sim_map
你好，请问这句代码到底有什么作用啊,他的前面不是已经有两个相乘了嘛，为什么还有这句代码啊
sim_map= torch.matmul(query, key)

**Comment by Shea192** [comment]
这个是一个放缩系数。比如说，本来sim_map的数值范围可能是（1，100），，乘以这个之后就变成了（0，1）。主要是为了方便计算吧，毕竟softmax里面有指数计算
