### ISSUE TITLE
Same transformation for query and key in APNB?

### ISSUE THREAD

**Issue by Jacobew** [MendelXu/ANN#16]
Hi, I found that the query and key in APNB share the same transformation, see [here](https://github.com/MendelXu/ANN/blob/f4eabeb27dbba5c9bdcf83d03776bffa34995666/models/seg/utils/apnb.py#L64), which seems to be different from the implementation depicted in Fig.3, where key and value share transformation. 
Why? And which is better?
Please correct me if I'm making mistake here. :)

**Comment by Jacobew** [comment]
And I also noticed that, in supplementary, it is said that adding a BN after W_o helps a lot in AFNB, but I can't see this line in afnb.py. Could you please point it out?
I'm also curious about the performance of using "AFNB alone" (does it means AFNB without BN, or AFNB without APNB?) compared to the full version. 
Do you mean "AFNB alone" is not helpful in semantic segmentation?

**Comment by jessemelpolio** [comment]
Hi, the implementation of sharing the query and key branch follows Fig. 3 in the arxiv version. 

Sorry for the misleading. We are meaning that when using AFNB alone (AFNB without APNB), it might work better to add a BN layer on top of W_o. Using AFNB with a BN layer at the tail and APNB together (which is approximately the Full model) seems not helpful to performance improvement.

**Comment by Jacobew** [comment]
Thanks for your quick reply!
Since I've observed degraded performance when using AFNB without APNB, which is somewhat weird and I hope to identify the effect of minor implementation difference here. 

> We are meaning that when using AFNB alone (AFNB without APNB), it might work better to add a BN layer on top of W_o. 

Do you add a BN layer on top of W_o when reporting the results in Table 6? (+AFNB at the middle block) 
If so, what's the mIoU without BN?

**Comment by Jacobew** [comment]
After checking my implementation, I did use a BN at the tail of  AFNB (see [here](https://github.com/MendelXu/ANN/blob/f4eabeb27dbba5c9bdcf83d03776bffa34995666/models/seg/utils/afnb.py#L132)) but got a degraded performance in object detection. 
The only difference is that I add the output of AFNB to stage5 feature other than concatenate them. 
Since non-local block is useful in both object detection and semantic segmentation, I believe the difference of task may not be the issue. Did you try it in object detection? Do you have some other findings after ICCV regarding the issue mentioned in your supplementary?

**Comment by jessemelpolio** [comment]
We haven't tried on other tasks. I think while using the idea of AFNB, we should be very cautious about whether it is a perfect fit for our problem. For example, sometimes, the two input features may be so different from each other (different stages or different domains) that under this case, the similarity between them is not as accurate or meaningful as we want. Besides, it can also become an issue when the input feature map size is too small where even a simple concatenation or addition operation is enough to achieve a reasonable accuracy. The idea of AFNB is somewhat interesting, however, I can see there lies many possible issues when applying it to other areas. 

We no longer investigated AFNB after ICCV but I can share some of my thoughts and later work here. AFNB can be seen as a way to fuse features but the question is, if there is not a good feature alignment between these features at the beginning, fusing the features from a distant area is dangerous, meaningless and may interfere the training process that finally leads to degraded performance. But the paradox is, when the features are nearly the same (the extreme situation is the two inputs are from the same source just as APNB) which is expected to better suit the case, AFNB is therefore reduced to APNB and loses its original purpose then. In short, AFNB is problematic to fuse features with large discrepancies but makes no difference from APNB when dealing with features from the same source. It is interesting to see if there are any techniques that can fill this gap. This is one of the reason that I consider to use [Semantic Flow](https://arxiv.org/abs/2002.10120) (my paper to present in ECCV2020) to align features from adjacent layers, considering the capacity of the proposed flow alignment module is enough to capture minor discrepancies between two adjacent feature maps. Semantic Flow can also be seen as a way of fusion and as far as I can see, it is more effective and has less potential problems than AFNB. If possible, you could try it in your case. My apologies if the above response seems orderless and makes you confuse. If you still have questions regarding this issue, you could write to my mailbox which is a more suitable place to talk about research ideas and for me to give more specific responses to your questions.

**Comment by Jacobew** [comment]
Thanks for your comments! They are really helpful and I will give it a go. :)

**Comment by nanmehta** [comment]
can you please tell, why we have taken only 110 anchor points? Why cant we just use 3,6 only or some other integer value?
