### ISSUE TITLE
trained_model on NYUv

### ISSUE THREAD

**Issue by karlcao** [MendelXu/ANN#17]
could you please release a trained model on NYUv2 dataset? I try to use your network with resnet101-dilated8 to train NYUv2 data,but can only reach 41%miou. Or could please add a trainning scripts on NYUv2.THANKS!

**Comment by karlcao** [comment]
batch size=6.    2gpus 1080ti.

**Comment by MendelXu** [comment]
Sorry, we do not have a backup for it. Maybe you can refer to [RefineNet](https://arxiv.org/abs/1611.06612) to check if your setting is the same as theirs. We adopt the same setting in our experiments.

**Comment by karlcao** [comment]
> Sorry, we do not have a backup for it. Maybe you can refer to [RefineNet](https://arxiv.org/abs/1611.06612) to check if your setting is the same as theirs. We adopt the same setting in our experiments.

the original refinenet apply test-time multi-scale evaluation. did you use too?

**Comment by MendelXu** [comment]
No. We are not sure of the setting of the testing scales.
