### ISSUE TITLE
关于apnb模块中的 self.f_query = self.f_key？

### ISSUE THREAD

**Issue by swjtulinxi** [MendelXu/ANN#18]
你好，请问在apnb中此处权重共享，此处设置与nonlocal和afnb中不一样，请问使self.f_query = self.f_key是否会对结果造成影响

**Comment by MendelXu** [comment]
您好，我们在较小尺度上的实验显示影响不大，但是这种形式参数量要小一些，因此我们最终就采用了这种设计。

**Comment by swjtulinxi** [comment]
hi ,i have a question about the contextual module in Semantic segmentation ,such as your apbn, ppm,aspp and so on, Why I use and not use this module has no effect on the results，Does the size of batchsize affect the accuracy of the context module

**Comment by MendelXu** [comment]
I am not sure why the context modules make no effect on your project. But according to my experience, batch size affect the performance of a semantic segmentation model a lot, even without a context module.
