### ISSUE TITLE
When will the source code be released?

### ISSUE THREAD

**Issue by yukkyo** [MendelXu/ANN#2]
Nice paper ! 😆 

When will the source code be released?
I'm trying to implement it now, but I don't know the details of implementation.
So I want to refer to your source code.

**Comment by MendelXu** [comment]
Thanks for your attention. Sorry for the late reply as we were busy with other work before. It'll take a week or so before releasing the code.

**Comment by yukkyo** [comment]
Sorry for hurrying. I'm looking forward to it !
